services:

  fred_app:
    build: .
    ports:
    - 5000:5000
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"

  postgresql:
    volumes:
      - db_data:/var/lib/postgresql/data
    image: postgresql
    restart: always
    ports:
      - 5432:5432
    env_file:
      - compose_vars.env
    environment:
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    secrets:
      - postgres_password 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgresql"

volumes:
  db_data:

secrets:
  postgres_password:
    file: #path to file