---
name: testing-fred-app
on: 
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
    job1:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-22.04
        steps: 
            - name: checkout actions
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v5
              with: 
                python-version: '>=3.8.10'
            - name: Run tests
              run: python3 tests.py
            - name: Job has been successful
              if: ${{ success() }}
              run: echo "Succesful job"
